import Navbar from "@/components/main/nav/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/main/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "중소기업 ESG컨설팅 | ESG Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
